services:
  # Бэкенд сервис
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: nareshka-backend
    restart: unless-stopped
    environment:
      # База данных
      - DATABASE_URL=${DATABASE_URL}
      # Redis
      - REDIS_URL=${REDIS_URL}
      # JWT и сессии
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      # Сервер
      - PORT=4000
      - HOST=0.0.0.0
      - DEBUG=${DEBUG:-false}
      # WebDAV
      - WEBDAV_URL=${WEBDAV_URL}
      - WEBDAV_USERNAME=${WEBDAV_USERNAME}
      - WEBDAV_PASSWORD=${WEBDAV_PASSWORD}
      # CORS - разрешаем фронтенд
      - ALLOWED_ORIGINS=http://frontend,https://${DOKPLOY_DOMAIN:-localhost}
    ports:
      - "4000:4000"
    volumes:
      # Используем ../files для персистентности данных как рекомендует Dokploy
      - "../files/backend-logs:/app/logs"
      - "../files/backend-uploads:/app/uploads"
    networks:
      - nareshka-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Фронтенд сервис
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: nareshka-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - nareshka-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  nareshka-network:
    driver: bridge

volumes:
  # Используем именованные volumes для данных
  backend-logs:
    driver: local
  backend-uploads:
    driver: local
