from_latest_tag = false
ignore_merge_commits = false
disable_changelog = false
disable_bump_commit = false
generate_mono_repository_global_tag = true
generate_mono_repository_package_tags = true
branch_whitelist = []
skip_ci = "[skip ci]"
skip_untracked = false
pre_bump_hooks = []
post_bump_hooks = ["uv build"]
pre_package_bump_hooks = []
post_package_bump_hooks = []
tag_prefix = "v"

[git_hooks.commit-msg]
script = """#!/bin/sh
set -e
cog verify --file $1
cog check
"""


[commit_types]

[changelog]
path = "CHANGELOG.md"
authors = [{ signature = "Sergey Parfenyuk", username = "sparfenyuk" }]
template = "remote"
remote = "github.com"
owner = "sparfenyuk"
repository = "mcp-telegram"

[bump_profiles]
