"""Allow nullable userId in CodeExecution

Revision ID: 42c1e4093aa2
Revises: bcbb5b411c42
Create Date: 2025-06-14 15:40:24.502528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42c1e4093aa2'
down_revision = 'bcbb5b411c42'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('CodeExecution', 'userId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('UserCodeSolution_lastExecutionId_fkey', 'UserCodeSolution', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('UserCodeSolution_lastExecutionId_fkey', 'UserCodeSolution', 'CodeExecution', ['lastExecutionId'], ['id'], ondelete='SET NULL')
    op.alter_column('CodeExecution', 'userId',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ### 

