"""Update indexes for new architecture

Revision ID: 8aa94f4d5a35
Revises: 5563f9444a1b
Create Date: 2025-07-07 13:54:22.371654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aa94f4d5a35'
down_revision = '5563f9444a1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_codeexecution_createdat'), table_name='CodeExecution')
    op.create_index('idx_learningpath_orderindex', 'LearningPath', ['orderIndex'], unique=False)
    op.drop_index(op.f('idx_taskattempt_issuccessful'), table_name='TaskAttempt')
    op.drop_index(op.f('idx_testcase_active'), table_name='TestCase')
    op.create_index('idx_testcase_ispublic', 'TestCase', ['isPublic'], unique=False)
    op.create_index('idx_testcase_orderindex', 'TestCase', ['orderIndex'], unique=False)
    op.drop_index(op.f('idx_testvalidation_attemptid'), table_name='TestValidationResult')
    op.drop_index(op.f('idx_testvalidation_testcaseid'), table_name='TestValidationResult')
    op.create_index('idx_testvalidationresult_attemptid', 'TestValidationResult', ['attemptId'], unique=False)
    op.create_index('idx_testvalidationresult_passed', 'TestValidationResult', ['passed'], unique=False)
    op.create_index('idx_testvalidationresult_testcaseid', 'TestValidationResult', ['testCaseId'], unique=False)
    op.create_index('idx_testvalidationresult_testcaseid_attemptid', 'TestValidationResult', ['testCaseId', 'attemptId'], unique=True)
    op.drop_index(op.f('idx_usercategoryprogress_lastactivity'), table_name='UserCategoryProgress')
    op.drop_index(op.f('idx_usercodesolution_userid_blockid_languageid'), table_name='UserCodeSolution')
    op.create_index('idx_usercodesolution_userid_blockid', 'UserCodeSolution', ['userId', 'blockId'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_usercodesolution_userid_blockid', table_name='UserCodeSolution')
    op.create_index(op.f('idx_usercodesolution_userid_blockid_languageid'), 'UserCodeSolution', ['userId', 'blockId', 'languageId'], unique=True)
    op.create_index(op.f('idx_usercategoryprogress_lastactivity'), 'UserCategoryProgress', ['lastActivity'], unique=False)
    op.drop_index('idx_testvalidationresult_testcaseid_attemptid', table_name='TestValidationResult')
    op.drop_index('idx_testvalidationresult_testcaseid', table_name='TestValidationResult')
    op.drop_index('idx_testvalidationresult_passed', table_name='TestValidationResult')
    op.drop_index('idx_testvalidationresult_attemptid', table_name='TestValidationResult')
    op.create_index(op.f('idx_testvalidation_testcaseid'), 'TestValidationResult', ['testCaseId'], unique=False)
    op.create_index(op.f('idx_testvalidation_attemptid'), 'TestValidationResult', ['attemptId'], unique=False)
    op.drop_index('idx_testcase_orderindex', table_name='TestCase')
    op.drop_index('idx_testcase_ispublic', table_name='TestCase')
    op.create_index(op.f('idx_testcase_active'), 'TestCase', ['isActive'], unique=False)
    op.create_index(op.f('idx_taskattempt_issuccessful'), 'TaskAttempt', ['isSuccessful'], unique=False)
    op.drop_index('idx_learningpath_orderindex', table_name='LearningPath')
    op.create_index(op.f('idx_codeexecution_createdat'), 'CodeExecution', ['createdAt'], unique=False)
    # ### end Alembic commands ### 

