import { defineConfig } from 'orval';

export default defineConfig({
  nareshka: {
    input: '../back/openapi.json',
    output: {
      target: 'src/shared/api/generated/api.ts',
      client: 'react-query',
      mode: 'single',
      mock: false,
      clean: true,
      prettier: false,
      override: {
        mutator: {
          path: 'src/shared/api/base.ts',
          name: 'apiClient',
        },
        query: {
          useQuery: true,
          useMutation: true,
          signal: true,
          shouldExportHttpClient: true,
          shouldExportMutatorHooks: true,
        },
        operations: {},
        components: {
          schemas: {
            suffix: 'Type',
          },
        },
        header: (info) => [
          '/**',
          ` * Generated by orval v.7.10.0 🍻`,
          ` * Do not edit manually.`,
          ` * ${info.title}`,
          ` * ${info.description}`,
          ' */',
        ],
      },
    },
  },
});
